import './globals.css'
import { Inter } from 'next/font/google'
import Context from './context'
import ChatContext from './chatcontext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        
        <Context>
        <ChatContext>
          {children}
          </ChatContext>
        </Context>
        
        </body>
    </html>
  )
}
